name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: boost
      run: |
        # Use the boost_1_72_0-msvc-14.1-64.exe for Windows 2016
        $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
        (New-Object System.Net.WebClient).DownloadFile($Url, "$env:TEMP\boost.exe")
        Start-Process -Wait -FilePath "$env:TEMP\boost.exe" "/SILENT","/SP-","/SUPPRESSMSGBOXES","/DIR=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake -DBOOST_ROOT="C:\hostedtoolcache\windows\Boost\1.72.0" ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2
    - name: Test
      working-directory: build
      run: ctest -j2
